### ISSUE TITLE
Remove index in registry connection file ? 

### ISSUE THREAD

**Issue by tloubrieu-jpl** [NASA-PDS/registry-common#48]
### 💡 Description

TO BE CONFIRMED: but my initial proposal is to remove the index specification from the connection file so that,
1. in registry-manager, the -index option is still used 
2. in harvest, the discipline node in the job configuration is used to select the index. For example SBNUMD --> sbnumd-registry, sbnumd-registry-refs...

**Comment by tloubrieu-jpl** [comment]
@al-niessner , @jordanpadams can you let me know what you think of this update ? Something is needed because currently there are multiple places where the index can be configured and if we keep them as-is that will be confusing for the users and difficult to document, but beside what I am proposing there might be other options.

**Comment by jordanpadams** [comment]
@tloubrieu-jpl I agree with this proposal. The end user should not have to care about the registry index.

**Comment by jordanpadams** [comment]
> in registry-manager, the -index option is still used

Should we abstract this away as well to key off of the node instead?

**Comment by al-niessner** [comment]
@tloubrieu-jpl @jordanpadams 

If I am reading your proposal correctly, you want to remove the registry index name from the XML and use `-index` for the tools. I think the other way round is more appropriate -> get rid of `-index` from all tools and use the registry index name in the XML.

In the case of cognito, the group one belongs to restricts access to the registry index. For instance JAXA cannot write to PDS_SBN or vice versa. The access is controlled through cognito but the logical separation is controlled through the registry index name. Keeping these together in the XML keeps the concepts together.

Second, if the name of the tables change or how we use them, make a list of them for instance to support registry-api, then there is one place that does this: the XML configuration file. If `-index` then lots of code has to rewritten as they do not share command line parsing code other than some general tool. In other words, there is no single piece of code of all `-index` set up or handling. Mostly just cut and paste but not even that good.

Fixing the registry names to be <node-name>-registry{-dd,-refs} is doable, but then all tools etc would have to know about node names. Right now harvest is the only tool that uses node name.

I purposely built the connection XML so that we can provide it to the user in the registry-common artifact as `app://connection/cognito/<node name>.xml`. It then allows us to pick and chose registry naming and hide it. If we change, then we deliver new artifacts and nobody knows or has to change. It also allows developers to have their own space without having to add them to the node name list in harvest. Maybe not needed in harvest anymore?

**Comment by al-niessner** [comment]
@jordanpadams @tloubrieu-jpl 

What is the decision here? Do we need to chat about this today? I would like to make this my priority and pull of the `-index` from the registry-mgr commands.

**Comment by jordanpadams** [comment]
@al-niessner I think what @tloubrieu-jpl is getting at here is do we have a specific reason we can't just assume the index information from what we know about the system?

Our end users don't know or care what index they are writing to, they just want to write some data somewhere, and then search it. Putting this kind of a information in a user config just bring about more questions than answers. If we want to keep this in a config, can we create a separate internal config separate from the user config?

**Comment by tloubrieu-jpl** [comment]
Hi @al-niessner, @jordanpadams,

I understand the Al's point of view, as the development would be simpler and more robust.

In registry-mgr the administration tasks (e.g. create-registry) will be slightly more complicated since one will need to update the connection file instead of using the CLI argument, but that would be more simple for the actual users in the nodes who always use the same index, so I am good with that.

@jordanpadams, each user would have their own configuration file, that we can prepare for them. It only needs to be written once.

**Comment by al-niessner** [comment]
@jordanpadams @tloubrieu-jpl 

The only reason to update the connection for registry-mgr is to do a personal developement index but it only need be done once. We can always deploy `app://connection/.../development.tl.xml` and `app://connection/.../development.afn.xml` and etc. It is the user name and password that prevent you writing to my index and me to yours.

Doing admin on jaxa and the rest, just use their connection.

**Comment by jordanpadams** [comment]
@tloubrieu-jpl @al-niessner sounds good. If you could update this ticket with the plan and/or close as wontfix that would be excellent!

**Comment by al-niessner** [comment]
@jordanpadams @tloubrieu-jpl 

Plan:

1. remove all `-index` in registry-mgr tools and use the one in connection
2. create a connection (cognito) for each 'node' in harvest as a registry-common resource
3. add developement to connections as well if desired - just cognito because `app://connection/direct/localhost.xml` works with docker just fine so already user independent.
4. add connections for pds-eng too
5. remove 'node' from harvest config
